dist: trusty
language: node_js
node_js:
- "12"

script:
- npm run lint
- npm test

# run samples
- bin/curlf -v samples/pets-json.curlf
- bin/curlf -v samples/pets-with-protocol.curlf
- bin/curlf -v samples/pets.curlf
- bin/curlf -v samples/requestbin.curl
- bin/curlf -v samples/sample.curlf
- bin/curlf -v samples/swapi.curlf

# test input from stdin
- |
    bin/curlf -v --in <<EOF
    GET https://www.zaragoza.es/sede/servicio/mascotas
    Accept: application/json
    EOF
